Default:           # Stack name. This should be unique and idelaly not same as stage
  Module:
    From: src.default.default          # this is the python package that contains the stack class
    Import: Default                    # this is the python class that implements the stack. 

  EnvironmentList:  # use this deployment mode  to specify a list of 'environments' to deploy this stack to. 
  - Account: <<account>> 
    Region:  <<region>>
    EnvParameters:          # OPTIONAL these will be only to this environment. All these are specific to the type of stack you deploy
      name: default