AdditionalPolicy: # policys that your pipeline build needs to do its work.

  - description: switch roles to target accoutnts for synth
    actions:
    - sts:GetServiceBearerToken
    - sts:GetSessionToken
    - sts:AssumeRole
    effect: ALLOW
    resources:
    - '*' #You may need/want to consider restricting this. 

  - description: Permission to get a Docker Image from ECR
    actions:
    - ecr:GetAuthorizationToken 
    - ecr:GetDownloadUrlForLayer
    - ecr:BatchGetImage
    - ecr:BatchCheckLayerAvailability
    effect: ALLOW
    resources:  
    - '*'     #You may need/want to consider restricting this. 

  - description: Permission to read CandIPyPI
    actions:
    - codeartifact:GetPackageVersionReadme
    - codeartifact:ListTagsForResource
    - codeartifact:DescribeRepository
    - codeartifact:ListPackageVersionAssets
    - codeartifact:DescribeDomain
    - codeartifact:ListRepositoriesInDomain
    - codeartifact:DescribePackageVersion
    - codeartifact:GetDomainPermissionsPolicy
    - codeartifact:ListPackageVersionDependencies
    - codeartifact:ListPackages
    - codeartifact:GetAuthorizationToken
    - codeartifact:ReadFromRepository
    - codeartifact:GetRepositoryEndpoint
    - codeartifact:GetPackageVersionAsset
    - codeartifact:GetRepositoryPermissionsPolicy
    - codeartifact:ListPackageVersions
    effect: ALLOW
    resources:
    - 'arn:aws:codeartifact:*:283923818425:package/*/*/*/*/*'
    - 'arn:aws:codeartifact:ap-southeast-2:283923818425:domain/contactenergy'
    - 'arn:aws:codeartifact:ap-southeast-2:283923818425:repository/contactenergy/CandIPyPI'
  
  - description: List Repos and Domains
    actions:
    - codeartifact:ListRepositories
    - codeartifact:ListDomains
    effect: ALLOW
    resources:
    - '*'
  
  - description: Session Manager for debugging
    actions:
    - ssmmessages:CreateControlChannel
    - ssmmessages:CreateDataChannel
    - ssmmessages:OpenControlChannel
    - ssmmessages:OpenDataChannel
    effect: ALLOW
    resources:
    - '*'
    
Environment:   
  Privileged: True    # if you are bundling lambdas or building docker images, the build stage needs to be running in privilidged mode. 
  ComputeType: LARGE  # SMALL (3GB/2vcpu)| MEDIUM (7GB/4cpu) | LARGE (16GB/8Vcpu) | X2_LARGE (145GB/72BVcpu)